language: node_js

node_js:
- '6'

install:
- npm install

script:
- npm run lint
- npm run test
- npm run build

deploy:
  provider: surge
  project: ./dist/
  domain: https://glmr-synth.surge.sh
  skip_cleanup: true

after_deploy:
- openssl aes-256-cbc -K $encrypted_6bdb3c89b407_key -iv $encrypted_6bdb3c89b407_iv
  -in ./.travis/deploy_key.enc -out ./.travis/deploy_key.pem -d
- git pull
- npm version --no-git-tag-version minor
- git commit -am "Bump minor [ci skip]"
- chmod 600 .travis/deploy_key.pem
- eval "$(ssh-agent -s)"
- ssh-add .travis/deploy_key.pem
- git remote add deploy git@github.com:jimenglish81/glimmer-synth.git
- git push deploy
